### ISSUE TITLE
no instance is detected

### ISSUE THREAD

**Issue by loubron23** [hughw19/NOCS#79]
When I run the detect code, the problem of no instance is detected will appear, and an error will be reported when a certain image is detected:
Image id: 52
data/real/test/scene_1/0054
data/gts/real_test/results_real_test_scene_1_0054.pkl
predict result:
0.96875 0.96875 0.96875
Traceback (most recent call last):
   File "detect_eval.py", line 249, in &lt;module&gt;
     detect_result = model.detect([image], verbose=0)
   File "/rootCS/model.py", line 4394, in detect
     image.shape, windows[i])
   File "/rootCS/model.py", line 4335, in unmold_detections
     full_mask = utils.unmold_mask(masks[i], boxes[i], image_shape)
   File "/rootCS/utils.py", line 1222, in unmold_mask
     mask, (y2 - y1, x2 - x1), interp='bilinear').astype(np.float32) / 255.0
   File "/root/anaconda3/envs/py356/lib/python3.5/site-packages/numpy/lib/utils.py", line 101, in newfunc
     return func(*args, **kwds)
   File "/root/anaconda3/envs/py356/lib/python3.5/site-packages/scipy/misc/pilutil.py", line 565, in imresize
     imnew = im.resize(size, resample=func[interp])
   File "/root/anaconda3/envs/py356/lib/python3.5/site-packages/PIL/Image.py", line 1929, in resize
     return self._new(self.im.resize(size, resample, box))
ValueError: height and width must be &gt; 0
I checked that the input of the image is correct. I want to know what the problem is. Is it because my environment is configured incorrectly?

**Comment by microchila** [comment]
ME TOO, WHY????!!!!

**Comment by loubron23** [comment]
> ME TOO, WHY????!!!!

I still can't solve the problem. I guess it may be the environment problem(cuda, gpu)? If you solve it, please tell me!

**Comment by Tianyi20** [comment]
> loubron23

HI, Did you solve the problem? I also encounter something going wild:
```

**************************************************
Image id:  0
data/real/test/scene_1/0000
data/gts/real_test/results_real_test_scene_1_0000.pkl
WARNING:tensorflow:From /home/xiangtianyi/anaconda3/envs/category/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py:422: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

2024-11-18 23:39:37.881917: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
2024-11-18 23:39:37.929959: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2024-11-18 23:39:38.145782: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2024-11-18 23:41:17.129222: E tensorflow/stream_executor/cuda/cuda_driver.cc:828] failed to allocate 3.04G (3264020480 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2024-11-18 23:41:17.682929: W tensorflow/core/common_runtime/bfc_allocator.cc:237] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.28GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2024-11-18 23:41:17.682962: W tensorflow/core/common_runtime/bfc_allocator.cc:237] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.28GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
predict result:
0.96875 0.96875 0.96875

Detection takes 100.655053s.
No instance is detected.
Aligning predictions...
New alignment takes 0.000012s.
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
Results of image test_scene_1_0000 has been saved to output/real_test_20241118T2339/results_test_scene_1_0000.pkl.
Takes 100.81024813652039 to finish this image.
/home/xiangtianyi/anaconda3/envs/category/lib/python3.5/site-packages/numpy/core/fromnumeric.py:3335: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/xiangtianyi/anaconda3/envs/category/lib/python3.5/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Alignment average time:  nan


**************************************************
Image id:  1
data/real/test/scene_1/0001
data/gts/real_test/results_real_test_scene_1_0001.pkl
/home/xiangtianyi/NOCS_CVPR2019/utils.py:573: RuntimeWarning: overflow encountered in multiply
  height *= np.exp(deltas[:, 2])
/home/xiangtianyi/NOCS_CVPR2019/utils.py:574: RuntimeWarning: overflow encountered in multiply
  width *= np.exp(deltas[:, 3])
/home/xiangtianyi/NOCS_CVPR2019/utils.py:578: RuntimeWarning: invalid value encountered in add
  y2 = y1 + height
/home/xiangtianyi/NOCS_CVPR2019/utils.py:579: RuntimeWarning: invalid value encountered in add
  x2 = x1 + width
/home/xiangtianyi/NOCS_CVPR2019/model.py:714: RuntimeWarning: overflow encountered in multiply
  refined_rois *= np.array([height, width, height, width])
predict result:
0.96875 0.96875 0.96875

Detection takes 0.098183s.
No instance is detected.
Aligning predictions...
New alignment takes 0.000023s.
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
Results of image test_scene_1_0001 has been saved to output/real_test_20241118T2339/results_test_scene_1_0001.pkl.
Takes 0.19923043251037598 to finish this image.
Alignment average time:  nan


**************************************************
Image id:  2
data/real/test/scene_1/0002
data/gts/real_test/results_real_test_scene_1_0002.pkl
predict result:
0.96875 0.96875 0.96875

Detection takes 0.090365s.
No instance is detected.
Aligning predictions...
New alignment takes 0.000023s.
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
Results of image test_scene_1_0002 has been saved to output/real_test_20241118T2339/results_test_scene_1_0002.pkl.
Takes 0.19266009330749512 to finish this image.
Alignment average time:  nan


**************************************************
```
